name: pypi

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: config
      run: |
        RELEASE=${GITHUB_REF##*/}
        sed -i -e "s/version = \".*\"/version = \"$RELEASE\"/" pyproject.toml
        echo $RELEASE
    - name: Install pip, setuptools, build, twine
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m build
        twine upload dist/*