
name: Test
on:
  push:

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    steps:
      - uses: actions/checkout@v6
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --dev
      - name: Run tests
        run: uv run coverage run manage.py test -v 2